# Generated by Django 4.2.6 on 2023-10-31 07:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Profile",
            new_name="User",
        ),
    ]
