# Generated by Django 4.2.6 on 2023-10-31 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_profile_delete_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="profile_image",
            field=models.ImageField(
                blank=True, upload_to="accounts/profile_img/%Y/%m/%d/"
            ),
        ),
    ]
