# Generated by Django 4.2.6 on 2023-10-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_tag_post_view_count_comment_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
