# Generated by Django 4.2.6 on 2023-10-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tag",
            field=models.ManyToManyField(to="blog.tag"),
        ),
    ]
