# Generated by Django 4.2.6 on 2023-11-01 00:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0008_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="authoer",
            new_name="author",
        ),
    ]
