# Generated by Django 4.2.6 on 2023-11-01 09:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0010_comment_parent_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="parent_comment",
            new_name="nested_reply",
        ),
    ]
